# Question 1

In [49]:
def vander_return(input_array, N):
  ## This is using vander function
  return np.vander(input_array, N)

In [58]:
vander_return(np.array([1,2,3,4]), 4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [86]:
def vander_return_manual(input_array, N):
  # This is vander manual implementation
  if(N > input_array.shape[0]):
    return "N larger than input shape not possible"
  output = np.empty(shape=(input_array.shape[0],N))
  output.fill(0)
  for count, i in enumerate(range(N-1,-1,-1)):
    output[:,count] = np.power(input_array, i)
  return output

In [87]:
vander_return_manual(np.array([2,3,4]), 3)

array([[ 4.,  2.,  1.],
       [ 9.,  3.,  1.],
       [16.,  4.,  1.]])

In [88]:
vander_return_manual(np.array([1, 2, 3, 5]), 3)

array([[ 1.,  1.,  1.],
       [ 4.,  2.,  1.],
       [ 9.,  3.,  1.],
       [25.,  5.,  1.]])

# Question 2

### Moving averages

In [14]:
import numpy as np

In [45]:
def moving_average(input, k):
  y = []
  for i in range(input.shape[0]):
    if((i+k) <= input.shape[0]):
      y.append(np.ma.average(input[i:i+k]))
    else:
      break
  return y

In [47]:
moving_average(np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]), 3)

[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333,
 116.33333333333333]

7